# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'film_des.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 622)
        MainWindow.setMinimumSize(QtCore.QSize(0, 50))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.497826, y1:1, x2:0.492537, y2:0.023, stop:0 rgba(99, 99, 99, 255), stop:1 rgba(0, 0, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(240, 90, 331, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(182, 1, 13);\n"
"background-color: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.l = QtWidgets.QLineEdit(self.page)
        self.l.setGeometry(QtCore.QRect(240, 210, 339, 50))
        self.l.setMinimumSize(QtCore.QSize(0, 50))
        self.l.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"\n"
"\n"
"")
        self.l.setText("")
        self.l.setObjectName("l")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 280, 339, 50))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 380, 339, 34))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(182, 1, 13);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(420, 420, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: red;\n"
"background-color: transparent;\n"
"border: none; ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_12 = QtWidgets.QPushButton(self.page)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 330, 331, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("color: red;\n"
"background-color: transparent;\n"
"border: none; ")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(240, 420, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: red;\n"
"background-color: transparent;")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.l_2 = QtWidgets.QLineEdit(self.page_2)
        self.l_2.setGeometry(QtCore.QRect(230, 130, 339, 50))
        self.l_2.setMinimumSize(QtCore.QSize(0, 50))
        self.l_2.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"\n"
"\n"
"")
        self.l_2.setText("")
        self.l_2.setObjectName("l_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 270, 339, 50))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 200, 339, 50))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_4.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 340, 339, 50))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_5.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(398, 410, 171, 34))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: rgb(182, 1, 13);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(239, 219, 191);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 410, 171, 34))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(172, 48, 48);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tabWidget = QtWidgets.QTabWidget(self.page_3)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color: black; color: rgb(182, 1, 13);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(50, 50, 309, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("color:  rgb(182, 1, 13); background-color:white;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(50, 120, 681, 351))
        self.listWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget.setStyleSheet("color:white; background-color: rgb(182, 1, 13);")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(520, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("color:  rgb(182, 1, 13); background-color:white;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(150, 0, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:none;")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(30, 90, 511, 421))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(570, 420, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(570, 120, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(570, 280, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(570, 350, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(570, 210, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 301, 151))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 310, 331, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setItalic(False)
        font.setUnderline(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(410, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(410, 80, 361, 445))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_7 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("background-color: transparent;")
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout.addWidget(self.radioButton_7, 2, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("background-color: transparent;")
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout.addWidget(self.radioButton_8, 9, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color: transparent;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 3, 0, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setStyleSheet("background-color: transparent;")
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout.addWidget(self.radioButton_9, 6, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: transparent;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: transparent;")
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("background-color: transparent;")
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 5, 0, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("background-color: transparent;")
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout.addWidget(self.radioButton_10, 7, 0, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setStyleSheet("background-color: transparent;")
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout.addWidget(self.radioButton_11, 10, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background-color: transparent;")
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 11, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(210, 30, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(182, 1, 13); background:none;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 190, 371, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 270, 371, 41))
        self.lineEdit_7.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_15.setGeometry(QtCore.QRect(480, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_16.setGeometry(QtCore.QRect(480, 270, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_17.setGeometry(QtCore.QRect(420, 460, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_18.setGeometry(QtCore.QRect(160, 460, 211, 61))
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(172, 48, 48);\n"
"border-radius: 15px;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(120, 60, 541, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(182, 1, 13);\n"
"background-color: none;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 350, 371, 41))
        self.lineEdit_8.setStyleSheet("QLineEdit {background-color: rgb(124, 124, 124);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"border:gray;\n"
"color:white;\n"
"border-radius: 15px;\n"
"transition: 1.5s all-in-ease;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"cursor : pointer;\n"
"border: 2px solid rgb(182, 1, 13);\n"
"}\n"
"")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_19.setGeometry(QtCore.QRect(480, 350, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setStyleSheet("background-color:  rgb(182, 1, 13); color:  rgb(239, 219, 191);\n"
"border-radius: 15px;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setGeometry(QtCore.QRect(90, 400, 371, 16))
        self.label_7.setStyleSheet("color: rgb(182, 1, 13);\n"
"background-color: none;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setGeometry(QtCore.QRect(90, 240, 361, 20))
        self.label_8.setStyleSheet("color: rgb(182, 1, 13);\n"
"background-color: none;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(90, 320, 361, 16))
        self.label_9.setStyleSheet("color: rgb(182, 1, 13);\n"
"background-color: none;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ფილმოგრაფი"))
        self.l.setPlaceholderText(_translate("MainWindow", "შეიყვანეთ  მეილი / მომხმარებელი"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "შეიყვანეთ პაროლი"))
        self.pushButton_2.setText(_translate("MainWindow", "შესვლა"))
        self.pushButton.setText(_translate("MainWindow", "რეგისტრაცია"))
        self.pushButton_12.setText(_translate("MainWindow", "დაგავიწყდა პაროლი?"))
        self.label_10.setText(_translate("MainWindow", "არ გაქვს ანგარიში?"))
        self.l_2.setPlaceholderText(_translate("MainWindow", "შეიყვანეთ მომხმარებლის სახელი"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "შეიყვანეთ პაროლი"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "შეიყვანეთ მეილი"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "გაიმეორეთ პაროლი"))
        self.pushButton_3.setText(_translate("MainWindow", "რეგისტრაცია"))
        self.pushButton_4.setText(_translate("MainWindow", "უკან დაბრუნება"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "შეიყვანე ფილმის სახელი"))
        self.pushButton_5.setText(_translate("MainWindow", "ძიება"))
        self.pushButton_10.setText(_translate("MainWindow", "არ იცი რას უყურო?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main page"))
        self.label_3.setText(_translate("MainWindow", "მომხმარებლის პროფილი"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "WATCH LATER"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FAVORITES"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "WATCHED"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_11.setText(_translate("MainWindow", "გასვლა"))
        self.pushButton_13.setText(_translate("MainWindow", "პროფილის \n"
"რედაქტირება"))
        self.pushButton_14.setText(_translate("MainWindow", "სტატისტიკა"))
        self.pushButton_7.setText(_translate("MainWindow", "ჩვენს შესახებ"))
        self.pushButton_8.setText(_translate("MainWindow", "დახმარება"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "User"))
        self.label_4.setText(_translate("MainWindow", "არ იცი \n"
"რას უყურო?"))
        self.pushButton_9.setText(_translate("MainWindow", "დააჭირე"))
        self.label_6.setText(_translate("MainWindow", "როგორია შენი განწყობა?"))
        self.radioButton_7.setText(_translate("MainWindow", "საშიში"))
        self.radioButton_8.setText(_translate("MainWindow", "თვითშემეცნება"))
        self.radioButton_3.setText(_translate("MainWindow", "სევდიანი"))
        self.radioButton_9.setText(_translate("MainWindow", "ნოსტალგიური"))
        self.radioButton_2.setText(_translate("MainWindow", "მოწყენილი"))
        self.radioButton.setText(_translate("MainWindow", "მხიარული"))
        self.radioButton_6.setText(_translate("MainWindow", "შეყვარებული"))
        self.radioButton_10.setText(_translate("MainWindow", "მჭირდება ინსპირაცია"))
        self.radioButton_11.setText(_translate("MainWindow", "საოჯახო დრო"))
        self.radioButton_5.setText(_translate("MainWindow", "გამაოცე"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Fun"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "ახალი სახელი"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "ახალი პაროლი"))
        self.pushButton_15.setText(_translate("MainWindow", "სახელის შეცვლა"))
        self.pushButton_16.setText(_translate("MainWindow", "პაროლის შეცვლა"))
        self.pushButton_17.setText(_translate("MainWindow", "პროფილის წაშლა"))
        self.pushButton_18.setText(_translate("MainWindow", "უკან დაბრუნება"))
        self.label_5.setText(_translate("MainWindow", "პროფილის რედაქტირება"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "ახალი მეილი"))
        self.pushButton_19.setText(_translate("MainWindow", "მეილის შეცვლა"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
